from django.urls import path, re_path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('taquilla-api/articulo/', views.ArticuloList.as_view()),
    url(r'^taquilla-api/articulo/(?P<pk>\d+)/edit/$',views.ArticuloUpdate.as_view()),
    url(r'^taquilla-api/articulo/(?P<pk>\d+)/delete/$',views.ArticuloDestroy.as_view()),
    url(r'^taquilla-api/articulo/(?P<pk>\d+)/$',views.ArticuloRetrieve.as_view()),
    path('taquilla-api/cliente/', views.ClienteList.as_view()),
    url(r'^taquilla-api/cliente/(?P<cedula>[-\w\d]+)/edit/$',views.ClienteUpdate.as_view()),
    url(r'^taquilla-api/cliente/(?P<cedula>[-\w\d]+)/delete/$',views.ClienteDestroy.as_view()),
    url(r'^taquilla-api/cliente/(?P<cedula>[-\w\d]+)/$',views.ClienteRetrieve.as_view()),
    path('taquilla-api/interes/', views.InteresList.as_view()),
    url(r'^taquilla-api/interes/(?P<pk>\d+)/edit/$',views.InteresUpdate.as_view()),
    url(r'^taquilla-api/interes/(?P<pk>\d+)/delete/$',views.InteresDestroy.as_view()),
    url(r'^taquilla-api/interes/(?P<pk>\d+)/$',views.InteresRetrieve.as_view()),
    path('taquilla-api/preparador/', views.PreparadorList.as_view()),
    url(r'^taquilla-api/preparador/(?P<cedula>[-\w\d]+)/edit/$',views.PreparadorUpdate.as_view()),
    url(r'^taquilla-api/preparador/(?P<cedula>[-\w\d]+)/delete/$',views.PreparadorDestroy.as_view()),
    url(r'^taquilla-api/preparador/(?P<cedula>[-\w\d]+)/$',views.PreparadorRetrieve.as_view()),
    path('taquilla-api/historialcuenta/', views.HistorialCuentaList.as_view()),
    url(r'^taquilla-api/historialcuenta/(?P<fecha>[-\w\d]+)/edit/$',views.HistorialCuentaUpdate.as_view()),
    url(r'^taquilla-api/historialcuenta/(?P<fecha>[-\w\d]+)/delete/$',views.HistorialCuentaDestroy.as_view()),
    url(r'^taquilla-api/historialcuenta/(?P<fecha>[-\w\d]+)/$',views.HistorialCuentaRetrieve.as_view()),
    path('taquilla-api/plataformapago/', views.PlataformaPagoList.as_view()),
    url(r'^taquilla-api/plataformapago/(?P<pk>\d+)/edit/$',views.InteresUpdate.as_view()),
    url(r'^taquilla-api/plataformapago/(?P<pk>\d+)/delete/$',views.InteresDestroy.as_view()),
    url(r'^taquilla-api/plataformapago/(?P<pk>\d+)/$',views.InteresRetrieve.as_view()),
    path('taquilla-api/transaccion/', views.TransaccionList.as_view()),
    url(r'^taquilla-api/transaccion/(?P<pk>\d+)/edit/$',views.TransaccionUpdate.as_view()),
    url(r'^taquilla-api/transaccion/(?P<pk>\d+)/delete/$',views.TransaccionDestroy.as_view()),
    url(r'^taquilla-api/transaccion/(?P<pk>\d+)/$',views.TransaccionRetrieve.as_view()),
    path('taquilla-api/venta/', views.VentaList.as_view()),
    url(r'^taquilla-api/venta/(?P<pk>\d+)/edit/$',views.VentaUpdate.as_view()),
    url(r'^taquilla-api/venta/(?P<pk>\d+)/delete/$',views.VentaDestroy.as_view()),
    url(r'^taquilla-api/venta/(?P<pk>\d+)/$',views.VentaRetrieve.as_view()),
    path('taquilla-api/deuda/', views.DeudaList.as_view()),
    url(r'^taquilla-api/deuda/(?P<pk>\d+)/edit/$',views.DeudaUpdate.as_view()),
    url(r'^taquilla-api/deuda/(?P<pk>\d+)/delete/$',views.DeudaDestroy.as_view()),
    url(r'^taquilla-api/deuda/(?P<pk>\d+)/$',views.DeudaRetrieve.as_view()),
    path('taquilla-api/pagodeuda/', views.PagoDeudaList.as_view()),
    url(r'^taquilla-api/pagodeuda/(?P<pk>\d+)/edit/$',views.PagoDeudaUpdate.as_view()),
    url(r'^taquilla-api/pagodeuda/(?P<pk>\d+)/delete/$',views.PagoDeudaDestroy.as_view()),
    url(r'^taquilla-api/pagodeuda/(?P<pk>\d+)/$',views.PagoDeudaRetrieve.as_view()),
    
]