# Generated by Django 2.1.2 on 2018-10-04 01:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Cedula invalida', regex='^[V|E|J|P][0-9]{5,9}$')])),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nombre invalido', regex="^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$")])),
                ('apellido', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Apellido invalido', regex="^[a-zA-Z]+(([',. -][a-zA-Z ])?[a-zA-Z]*)*$")])),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Telefono invalido', regex='\\(?([0-9]{4})\\)?([ .-]?)([0-9]{3})\x02([0-9]{4})')])),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Articulo')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialCuenta',
            fields=[
                ('fecha', models.DateTimeField(primary_key=True, serialize=False)),
                ('cant_ideal_efectivo', models.FloatField()),
                ('cant_ideal_caja', models.FloatField()),
                ('cant_real_efectivo', models.FloatField(default=0)),
                ('cant_real_caja', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Interes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField()),
                ('rango_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PagoDeuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoDeuda', models.FloatField(default=0)),
                ('tipoPago', models.CharField(max_length=30)),
                ('nro_confirmacion', models.IntegerField(default=None)),
                ('fecha_pago', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PlataformaPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Preparador',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('iniciales', models.CharField(default=None, max_length=3, validators=[django.core.validators.RegexValidator(message='Iniciales inválidas', regex='[A-Z]{2,3}')])),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nombre invalido', regex='[a-zA-Z]+')])),
                ('apellido', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Apellido invalido', regex='[a-zA-Z]+')])),
                ('cantidad_deuda', models.FloatField(default=0)),
                ('fecha_deuda', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('monto', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producto', models.IntegerField(default=0)),
                ('tipoPago', models.CharField(max_length=30)),
                ('nro_confirmacion', models.IntegerField(default=None)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Articulo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Cliente')),
                ('id_transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Transaccion')),
                ('plataforma_pago', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.PlataformaPago')),
                ('preparador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Preparador')),
            ],
        ),
        migrations.AddField(
            model_name='pagodeuda',
            name='id_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Transaccion'),
        ),
        migrations.AddField(
            model_name='pagodeuda',
            name='plataforma_pago',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.PlataformaPago'),
        ),
        migrations.AddField(
            model_name='pagodeuda',
            name='preparador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Preparador'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='id_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Transaccion'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='preparador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Preparador'),
        ),
    ]
