# Generated by Django 2.1.2 on 2018-12-21 00:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHistory',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('ideal_amount_cash', models.FloatField(default=0)),
                ('ideal_amount_account', models.FloatField(default=0)),
                ('real_amount_cash', models.FloatField(default=0)),
                ('real_amount_account', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id_document', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid id document', regex='^[V|E|J|P]\\-[0-9]{5,8}$')])),
                ('initials', models.CharField(default=None, max_length=3, validators=[django.core.validators.RegexValidator(message='Invalid initials', regex='[A-Z]{2,3}')])),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid first name', regex='^[a-zA-Záéíóúñ]+$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid last name', regex='^[a-zA-Záéíóúñ ]+$')])),
                ('email', models.EmailField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Invalid email', regex='([a-zA-Z0-9_-]+\\.?){1,}@[a-z]+\\.[a-z]{1,}')])),
                ('debt_amount', models.FloatField(default=0)),
                ('debt_date', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid name', regex='^[a-zA-Záéíóúñ ]+$')])),
                ('code', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_document', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid document id', regex='^[V|E|J|P]\\-[0-9]{5,8}$')])),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid first name', regex='^[a-zA-Záéíóúñ]+$')])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid last name', regex='^[a-zA-Záéíóúñ]+$')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid Phone', regex='[(]?\\d{3}[)]?\\s?-?\\s?\\d{3}\\s?-?\\s?\\d{4}')])),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(default=0)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Assistant')),
            ],
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_amount', models.FloatField(default=0)),
                ('confirmation_no', models.IntegerField(default=None)),
                ('pay_date', models.DateTimeField(default=datetime.datetime.now)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Assistant')),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=0)),
                ('range_days', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Invalid description', regex='^[a-zA-Záéíóúñ ]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Invalid name', regex='^[a-zA-Záéíóúñ/ ]+$')])),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(default=0)),
                ('confirmation_no', models.IntegerField(default=None)),
                ('notes', models.CharField(max_length=60, null=True)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Assistant')),
                ('bank', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Bank')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Client')),
                ('pay_method', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.PayMethod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.FloatField(default=None)),
                ('types', models.CharField(max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Tipo invalido', regex='^[a-zA-Záéíóúñ ]+$')])),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Transaction'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='pay_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.PayMethod'),
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Transaction'),
        ),
        migrations.AddField(
            model_name='debt',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Product'),
        ),
        migrations.AddField(
            model_name='debt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.Transaction'),
        ),
        migrations.AddField(
            model_name='bank',
            name='pay_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taquillaAPI.PayMethod'),
        ),
    ]
