# Generated by Django 2.1 on 2018-10-05 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taquillaAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Cedula invalida', regex='^[V|E|J|P][0-9]{5,9}$')]),
        ),
        migrations.AlterField(
            model_name='preparador',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Cedula invalida', regex='^[V|E|J|P][0-9]{5,9}$')]),
        ),
    ]
