# Generated by Django 2.1.2 on 2019-01-04 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taquillaAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='pay_method',
        ),
    ]
