# Generated by Django 2.1 on 2018-10-30 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taquillaAPI', '0003_auto_20181005_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nombre invalido', regex='[a-zA-Z]')]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Cedula invalida', regex='^[V|E|J|P]\\-[0-9]{5,9}$')]),
        ),
        migrations.AlterField(
            model_name='historialcuenta',
            name='cant_ideal_caja',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historialcuenta',
            name='cant_ideal_efectivo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interes',
            name='porcentaje',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='interes',
            name='rango_dias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preparador',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Cedula invalida', regex='^[V|E|J|P]\\-[0-9]{5,9}$')]),
        ),
        migrations.AlterField(
            model_name='preparador',
            name='fecha_deuda',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
