# Generated by Django 2.1 on 2018-10-31 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taquillaAPI', '0006_auto_20181031_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Tipo invalido', regex='[a-zA-Z]+')]),
        ),
    ]
