# Generated by Django 2.1 on 2018-10-31 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taquillaAPI', '0007_auto_20181031_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataformapago',
            name='codigo_banco',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
