# Generated by Django 2.1 on 2018-10-31 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taquillaAPI', '0008_plataformapago_codigo_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparador',
            name='correo',
            field=models.EmailField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Email invalido', regex='([a-zA-Z0-9_-]+\\.?){1,}@[a-z]+\\.[a-z]{1,}')]),
        ),
    ]
