# Generated by Django 2.1 on 2018-10-31 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taquillaAPI', '0010_auto_20181031_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparador',
            name='correo',
            field=models.EmailField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator(message='Email invalido', regex='([a-zA-Z0-9_-]+\\.?){1,}@[a-z]+\\.[a-z]{1,}')]),
        ),
    ]
